---
title: "[Discussion] "
body:
  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What would you like to discuss?
      placeholder: I'd like to discuss adding support for Wazuh SCA variables...
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - General Usage
        - Feature Idea
        - Wazuh SCA Policy
        - CI/CD
        - Other
    validations:
      required: true
